"""Finite recombination of every valid proposal generated by composite-merge.

The baseline search is unchanged. Its validated proposal rectangles form a
bounded set-cover pool; each selected rectangle must alone service a *whole*
required FE with every ordered addition. This is a finite-pool improvement,
not an engineering approval or a global lower bound.
"""
from __future__ import annotations

from dataclasses import replace
import math
from time import perf_counter

from .composite_merge import solve_composite_merge
from ..contracts.composite_coverage import (
    MONOTONE_COMPONENT_STO_COVERAGE_POLICY, MONOTONE_SINGLE_STO_COVERAGE_POLICY,
)
from ..contracts.composite_search import CompositeSearchPoint, CompositeSearchProblem, CompositeSearchResult
from ..services.composite_coverage import (
    MAX_CELL_ZONE_PAIRS, MAX_ZONES, evaluate_composite_coverage,
    monotone_component_recipe_covers, monotone_single_recipe_covers, recipe_covers,
)
from ..services.composite_host import evaluate_composite_host
from ..services.finite_cover import solve_finite_cover_front
from ..services.zone_tradeoff import recommend_zone_knee


def _whole_fe_coverage(problem, proposals, deadline, maximum_incidence_nnz):
    demand = problem.demand
    required = tuple(cell for cell in demand.cells if demand.level(cell.level_index).requires_extra)
    if perf_counter() >= deadline:
        return (), 0, "prep_timeout"
    cell_boxes = tuple((min(x for x, _ in cell.poly), min(y for _, y in cell.poly),
                        max(x for x, _ in cell.poly), max(y for _, y in cell.poly))
                       for cell in required)
    if perf_counter() >= deadline:
        return (), 0, "prep_timeout"
    covers = (monotone_component_recipe_covers
              if problem.policy_id == MONOTONE_COMPONENT_STO_COVERAGE_POLICY
              else monotone_single_recipe_covers
              if problem.policy_id == MONOTONE_SINGLE_STO_COVERAGE_POLICY else recipe_covers)
    # Recipe compatibility is independent of the rectangle. Do it once per level.
    compatible = {}
    for level in demand.levels:
        if not level.requires_extra:
            continue
        if perf_counter() >= deadline:
            return (), 0, "prep_timeout"
        compatible[level.index] = tuple(i for i, cell in enumerate(required)
                                        if covers(demand.level(cell.level_index).recipe, level.recipe))
    active, incidence_nnz = [], 0
    for index, (zone, check) in enumerate(proposals):
        if index % 16 == 0 and perf_counter() >= deadline:
            return (), incidence_nnz, "prep_timeout"
        served = []
        for i in compatible.get(zone.level_index, ()):
            required_recipe = demand.level(required[i].level_index).recipe
            boxes = check.component_service_bboxes_mm[:len(required_recipe.additions)]
            if len(boxes) != len(required_recipe.additions):
                continue
            lo_x = max(box[0] for box in boxes)
            lo_y = max(box[1] for box in boxes)
            hi_x = min(box[2] for box in boxes)
            hi_y = min(box[3] for box in boxes)
            cell_box = cell_boxes[i]
            if (lo_x <= cell_box[0] + 1e-6 and lo_y <= cell_box[1] + 1e-6
                    and hi_x >= cell_box[2] - 1e-6 and hi_y >= cell_box[3] - 1e-6):
                served.append(i)
        incidence_nnz += len(served)
        if incidence_nnz > maximum_incidence_nnz:
            return (), incidence_nnz, "incidence_limit"
        if served:
            active.append((zone, check, frozenset(served)))
    if not required:
        return (), incidence_nnz, "empty_demand"
    whole_cover = set().union(*(record[2] for record in active)) if active else set()
    if len(whole_cover) != len(required):
        return (), incidence_nnz, "uncoverable_whole_fe"
    return tuple(active), incidence_nnz, None


def _pareto(points):
    by_count = {}
    for point in points:
        count = len(point.zones)
        if count not in by_count or point.coverage.additional_mass_kg < by_count[count].coverage.additional_mass_kg - 1e-6:
            by_count[count] = point
    front, best = [], math.inf
    for count in sorted(by_count):
        point = by_count[count]
        if point.coverage.additional_mass_kg < best - 1e-6:
            front.append(point)
            best = point.coverage.additional_mass_kg
    return tuple(front)


def solve_composite_recombine(
    problem: CompositeSearchProblem, *, maximum_zones: int = 128,
    time_limit_s: float = 20, maximum_bar_length_mm: float = 11700,
    maximum_points: int = 16, progress_callback=None,
    neighbor_polish: bool = True, polish_time_limit_s: float = 5,
    polish_max_evaluations: int = 320, polish_max_steps: int = 8,
    gap_hierarchy: bool = True, recombine_time_limit_s: float = 5,
    maximum_pool_zones: int = 15000, maximum_incidence_nnz: int = 1000000,
    maximum_prep_s: float = 5,
) -> CompositeSearchResult:
    """Keep the full V3 baseline envelope and add at most two checked MILP points.

    The 5-second solver budget is shared by both caps. Pool and incidence limits
    are hard memory guards; failure leaves the complete baseline result intact.
    The output can have at most ``maximum_points + 2`` points; there is no
    second downsampling that could erase a baseline budget.
    """
    for name, value, upper in (("maximum_pool_zones", maximum_pool_zones, 15000),
                               ("maximum_incidence_nnz", maximum_incidence_nnz, 1000000)):
        if isinstance(value, bool) or not isinstance(value, int) or not 1 <= value <= upper:
            raise ValueError(f"{name} должен быть целым в диапазоне 1..{upper}")
    for name, value in (("recombine_time_limit_s", recombine_time_limit_s),
                        ("maximum_prep_s", maximum_prep_s)):
        if isinstance(value, bool) or not math.isfinite(value) or not 0 < value <= 60:
            raise ValueError(f"{name} должен быть положительным и не более 60 секунд")
    wrapper_started = perf_counter()
    proposals = {}
    pool_overflow = False

    def observe(zone, check):
        nonlocal pool_overflow
        key = (zone.demand_bbox, zone.level_index)
        prior = proposals.get(key)
        if prior is not None:
            if check.additional_mass_kg < prior[1].additional_mass_kg - 1e-9:
                proposals[key] = (zone, check)
            return
        if len(proposals) >= maximum_pool_zones:
            pool_overflow = True
            return
        proposals[key] = (zone, check)

    def base_progress(done, total):
        if progress_callback is not None:
            progress_callback(done, total + 1)

    base = solve_composite_merge(
        problem, maximum_zones=maximum_zones, time_limit_s=time_limit_s,
        maximum_bar_length_mm=maximum_bar_length_mm, maximum_points=maximum_points,
        progress_callback=base_progress if progress_callback is not None else None,
        neighbor_polish=neighbor_polish, polish_time_limit_s=polish_time_limit_s,
        polish_max_evaluations=polish_max_evaluations, polish_max_steps=polish_max_steps,
        gap_hierarchy=gap_hierarchy, _proposal_observer=observe)
    recombine_started = perf_counter()
    telemetry = dict(base.telemetry)
    telemetry["algorithm"] = "composite-bottom-up-plus-finite-recombine/v1"
    telemetry["scope"] = (base.telemetry["scope"]
                          + "_plus_finite_whole_fe_proposal_recombination")
    stats = {"status": "pending", "fallback_reason": None,
             "baseline_points": len(base.points), "extra_points": 0,
             "captured_unique_proposals": len(proposals), "maximum_pool_zones": maximum_pool_zones,
             "maximum_incidence_nnz": maximum_incidence_nnz, "maximum_prep_s": maximum_prep_s,
             "solve_time_limit_s": recombine_time_limit_s,
             "scope": "finite_validated_proposal_pool_whole_fe_set_cover_not_global_optimum"}
    telemetry["recombine"] = stats

    def fallback(reason):
        stats["status"] = "fallback"
        stats["fallback_reason"] = reason
        stats["retained_points"] = len(base.points)
        finished = perf_counter()
        stats["elapsed_s"] = finished - recombine_started
        telemetry["runtime_s"] = finished - wrapper_started
        if progress_callback is not None:
            progress_callback(telemetry["hierarchy_count"] + 1, telemetry["hierarchy_count"] + 1)
        return CompositeSearchResult(base.points, base.selected_index, telemetry)

    if not base.points:
        return fallback("no_baseline_front")
    if not base.points[0].zones:
        return fallback("empty_demand")
    if pool_overflow:
        return fallback("pool_limit")
    if not proposals:
        return fallback("no_valid_proposals")
    prep_started = perf_counter()
    active, nnz, reason = _whole_fe_coverage(
        problem, tuple(proposals.values()), prep_started + maximum_prep_s, maximum_incidence_nnz)
    stats.update(prep_s=perf_counter() - prep_started, active_proposals=len(active), incidence_nnz=nnz,
                 required_fe=sum(problem.demand.level(c.level_index).requires_extra for c in problem.demand.cells))
    proposals.clear()
    if reason:
        return fallback(reason)
    if perf_counter() >= prep_started + maximum_prep_s:
        return fallback("prep_timeout")
    required_count = stats["required_fe"]
    allowed = min(maximum_zones, MAX_ZONES, MAX_CELL_ZONE_PAIRS // len(problem.demand.cells))
    if allowed < 1:
        return fallback("cell_zone_limit")
    old_min = min(base.points, key=lambda p:p.coverage.additional_mass_kg)
    budgets = tuple(dict.fromkeys((allowed, min(allowed, len(old_min.zones)))))
    stats["budgets"] = budgets
    try:
        choices, solver_stats = solve_finite_cover_front(
            tuple(record[2] for record in active),
            tuple(record[1].additional_mass_kg for record in active),
            required_count, maximum_zones=allowed,
            time_limit_s=recombine_time_limit_s, budgets=budgets)
    except (ValueError, RuntimeError, MemoryError) as error:
        stats["solver_error_type"] = type(error).__name__
        return fallback("solver_error")
    stats["solver"] = solver_stats
    if not choices:
        return fallback("no_solver_solution")
    new_points = []
    for indexes in choices[:2]:
        zones = tuple(replace(active[index][0], id=f"MP-R-{index_in_solution}")
                      for index_in_solution, index in enumerate(indexes))
        if (len(zones) > allowed or len(zones) * len(problem.demand.cells) > MAX_CELL_ZONE_PAIRS
                or any(component.installed_length_mm > maximum_bar_length_mm + 1e-6
                       for zone in zones for component in zone.components)):
            stats.setdefault("rejected_solutions", []).append("limits")
            continue
        try:
            check = evaluate_composite_coverage(problem.demand, zones,
                policy_id=problem.policy_id, constraints=problem.constraints)
            if check.status != "pass":
                stats.setdefault("rejected_solutions", []).append("coverage")
                continue
            if problem.host_envelope is not None and "fail" in evaluate_composite_host(
                    problem.demand, zones, problem.host_envelope,
                    constraints=problem.constraints)["checks"].values():
                stats.setdefault("rejected_solutions", []).append("host")
                continue
        except ValueError:
            stats.setdefault("rejected_solutions", []).append("checker_error")
            continue
        new_points.append(CompositeSearchPoint(zones, check))
    if not new_points:
        return fallback("no_valid_recombined_point")
    front = _pareto((*base.points, *new_points))
    # Each former budget must retain a no-heavier solution at no greater count.
    for old in base.points:
        if not any(len(point.zones) <= len(old.zones)
                   and point.coverage.additional_mass_kg <= old.coverage.additional_mass_kg + 1e-6
                   for point in front):
            return fallback("old_budget_envelope_lost")
    assert len(front) <= maximum_points + 2
    recommendation = recommend_zone_knee(
        [(len(point.zones), point.coverage.additional_mass_kg) for point in front])
    telemetry.update(selection=recommendation, retained_front_count=len(front))
    stats.update(status="completed", fallback_reason=None, retained_points=len(front),
                 extra_points=sum(point in new_points for point in front),
                 full_checker_passed=len(new_points))
    finished = perf_counter()
    stats["elapsed_s"] = finished - recombine_started
    telemetry["runtime_s"] = finished - wrapper_started
    if progress_callback is not None:
        progress_callback(telemetry["hierarchy_count"] + 1, telemetry["hierarchy_count"] + 1)
    return CompositeSearchResult(front, recommendation["index"], telemetry)
