"""Публичный API оптимизации; внутренняя структура скрыта за стабильными импортами."""

from .adapters import MissingRebarSpecificationError, build_demand_map, build_layout_problem
from .algorithms import (
    AgglomerativeOptimizer,
    BspOptimizer,
    GreedyStripOptimizer,
    LayoutOptimizer,
    PriorityGreedyOptimizer,
    RowRunGreedyOptimizer,
    SpatialPartitionGreedyOptimizer,
    StripProfileDpOptimizer,
    StrongestBBoxOptimizer,
)
from .contracts import (
    AlgorithmRequest,
    DemandCell,
    DemandLevel,
    DemandMap,
    LayoutConstraints,
    LayoutEvaluation,
    LayoutMetrics,
    LayoutProblem,
    LayoutSolution,
    LayoutZone,
    ObjectiveWeights,
    SolutionStatus,
)
from .mappings import (
    PLATE_ZERO_D12,
    RebarBandMapping,
    RebarMapping,
    RebarMappingError,
    apply_rebar_mapping,
)
from .registry import OptimizerRegistry, built_in_optimizer_registry
from .services import (
    PLATE_11700_CATALOG,
    PLATE_11700_CUT_LENGTHS_MM,
    CutLengthCatalog,
    FixedDiameterAnchoragePolicy,
    bar_coordinates,
    bar_segments,
    build_zone,
    build_zone_from_bbox,
    demanded_cells,
    evaluate_layout,
)

__all__ = [
    "PLATE_ZERO_D12",
    "PLATE_11700_CATALOG",
    "PLATE_11700_CUT_LENGTHS_MM",
    "AgglomerativeOptimizer",
    "AlgorithmRequest",
    "BspOptimizer",
    "DemandCell",
    "DemandLevel",
    "DemandMap",
    "CutLengthCatalog",
    "FixedDiameterAnchoragePolicy",
    "GreedyStripOptimizer",
    "LayoutConstraints",
    "LayoutEvaluation",
    "LayoutMetrics",
    "LayoutOptimizer",
    "LayoutProblem",
    "LayoutSolution",
    "LayoutZone",
    "MissingRebarSpecificationError",
    "ObjectiveWeights",
    "OptimizerRegistry",
    "PriorityGreedyOptimizer",
    "RowRunGreedyOptimizer",
    "SpatialPartitionGreedyOptimizer",
    "RebarBandMapping",
    "RebarMapping",
    "RebarMappingError",
    "SolutionStatus",
    "StripProfileDpOptimizer",
    "StrongestBBoxOptimizer",
    "apply_rebar_mapping",
    "bar_coordinates",
    "bar_segments",
    "build_demand_map",
    "build_layout_problem",
    "build_zone",
    "build_zone_from_bbox",
    "built_in_optimizer_registry",
    "demanded_cells",
    "evaluate_layout",
]
